displayName=PvP Auto Entity Hider
author=Zach
description=Hides all players except your attacker while under attack in dangerous PvP areas
tags=pvp,wilderness,entity,hider
plugins=com.logicalsolutions.pvpentityhider.PvpEntityHiderPlugin